Repository microsoft/onefuzz, pull requests merged in 2020-12, with the labels that each got.

#347 Fix deployment of backdated versions of OneFuzz
  src/deployment/deploy.py
Labels: auto-merge

#348 Update deployment prerequisites to remove pyopenssl errors
  src/deployment/requirements.txt
Labels: auto-merge

#352 Use disable_check_debugger on asan integration tests
  src/integration-tests/integration-test.py
Labels: auto-merge

#353 add the instrumentation key to Info
  src/api-service/__app__/info/__init__.py
  src/api-service/__app__/onefuzzlib/azure/creds.py
  src/pytypes/onefuzztypes/responses.py
Labels: auto-merge

#351 Fail the task if parsing asan_log files fail
  src/agent/onefuzz/src/asan.rs
Labels: auto-merge

#355 use the correct instrumentation key
  src/api-service/__app__/onefuzzlib/azure/creds.py
Labels: auto-merge

#354 Simplify job template management workflow
  src/api-service/__app__/job_templates_manage/__init__.py
  src/api-service/__app__/job_templates_manage/function.json
  src/api-service/__app__/onefuzzlib/job_templates/templates.py
  src/cli/onefuzz/job_templates/manage.py
  src/pytypes/onefuzztypes/job_templates.py
  src/pytypes/onefuzztypes/validators.py
Labels: auto-merge

#359 Add support for ASAN print_scariness
  src/agent/onefuzz-agent/src/tasks/report/crash_report.rs
  src/agent/onefuzz-agent/src/tasks/report/generic.rs
  src/agent/onefuzz/data/libfuzzer-scariness-underflow.txt
  src/agent/onefuzz/data/libfuzzer-scariness.txt
  src/agent/onefuzz/src/asan.rs
  src/pytypes/onefuzztypes/models.py
Labels: auto-merge, internal-request

#360 fix job_templates deletion
  src/api-service/__app__/job_templates_manage/__init__.py
Labels: bug

#361 Document managing declarative templates
  docs/declarative-templates.md
  docs/managing-templates.md
Labels: documentation

#362 Add troubleshooting guide for the registration issue at deployment
  docs/known-issues.md
Labels: documentation

#366 Demonstrate a more complex template management
  docs/managing-templates.md
Labels: auto-merge
