Repository microsoft/onefuzz, pull requests merged in 2021-06, with the labels that each got.

#940 send NodeCommandStopIfFree on node shutdown
  src/api-service/__app__/onefuzzlib/workers/nodes.py
Labels: auto-merge, passed-integration-tests

#937 add an optional initial delay for heartbeats
  src/agent/onefuzz-agent/src/tasks/analysis/generic.rs
  src/agent/onefuzz-agent/src/tasks/config.rs
  src/agent/onefuzz-agent/src/tasks/coverage/libfuzzer_coverage.rs
  src/agent/onefuzz-agent/src/tasks/fuzz/generator.rs
  src/agent/onefuzz-agent/src/tasks/fuzz/libfuzzer_fuzz.rs
  src/agent/onefuzz-agent/src/tasks/fuzz/supervisor.rs
  src/agent/onefuzz-agent/src/tasks/heartbeat.rs
  src/agent/onefuzz-agent/src/tasks/merge/generic.rs
  src/agent/onefuzz-agent/src/tasks/merge/libfuzzer_merge.rs
  src/agent/onefuzz-agent/src/tasks/regression/generic.rs
  src/agent/onefuzz-agent/src/tasks/regression/libfuzzer.rs
  src/agent/onefuzz-agent/src/tasks/report/generic.rs
  src/agent/onefuzz-agent/src/tasks/report/libfuzzer_report.rs
  src/agent/onefuzz-supervisor/src/heartbeat.rs
  src/agent/onefuzz/src/heartbeat.rs
Labels: auto-merge, passed-integration-tests

#945 capture azcopy log file
  src/agent/onefuzz/src/az_copy.rs
Labels: auto-merge, passed-integration-tests

#947 Udpate adal error handling during deployment
  src/deployment/registration.py
Labels: auto-merge, passed-integration-tests

#948 handle azure-storage deleting nonexistent containers
  src/api-service/__app__/onefuzzlib/azure/containers.py
Labels: auto-merge, passed-integration-tests

#952 use deploy logging context for app creation logs
  src/deployment/deploy.py
  src/deployment/registration.py
Labels: auto-merge, passed-integration-tests

#939 work around issue with discriminated typed unions
  src/api-service/__app__/onefuzzlib/events.py
  src/api-service/__app__/requirements.txt
  src/api-service/tests/test_userinfo_filter.py
  src/cli/onefuzz/status/cache.py
  src/cli/onefuzz/status/top.py
  src/pytypes/onefuzztypes/events.py
  src/pytypes/requirements.txt
Labels: auto-merge, passed-integration-tests

#949 add `onefuzz jobs containers delete JOB_ID`
  src/cli/onefuzz/api.py
  src/cli/onefuzz/job_templates/handlers.py
  src/cli/onefuzz/template.py
  src/cli/onefuzz/templates/__init__.py
Labels: auto-merge, passed-integration-tests

#953 stabilize `onefuzz jobs containers download`
  src/cli/onefuzz/api.py
  src/cli/onefuzz/debug.py
Labels: auto-merge, passed-integration-tests

#954 remove unused adal import
  src/deployment/registration.py
Labels: auto-merge, passed-integration-tests

#763 Add generic coverage task
  docs/webhook_events.md
  src/agent/Cargo.lock
  src/agent/onefuzz-agent/Cargo.toml
  src/agent/onefuzz-agent/src/tasks/config.rs
  src/agent/onefuzz-agent/src/tasks/coverage/generic.rs
  src/agent/onefuzz-agent/src/tasks/coverage/mod.rs
  src/api-service/__app__/onefuzzlib/tasks/config.py
  src/api-service/__app__/onefuzzlib/tasks/defs.py
  src/cli/onefuzz/api.py
  src/cli/onefuzz/templates/libfuzzer.py
  src/pytypes/onefuzztypes/enums.py
  src/pytypes/onefuzztypes/models.py
Labels: auto-merge, passed-integration-tests

#941 libfuzzer fuzzing task perf improvements
  src/agent/onefuzz-agent/src/tasks/fuzz/libfuzzer_fuzz.rs
  src/agent/onefuzz/src/libfuzzer.rs
Labels: auto-merge, passed-integration-tests

#963 remove RequestBuilder abstraction in onefuzz-supervisor coordinator
  src/agent/onefuzz-supervisor/src/coordinator.rs
Labels: auto-merge, passed-integration-tests

#960 add `onefuzz debug job rerun JOB_ID` command
  src/cli/onefuzz/debug.py
Labels: auto-merge, passed-integration-tests

#967 handle scaleset resize exceptions
  src/api-service/__app__/onefuzzlib/azure/vmss.py
Labels: auto-merge, passed-integration-tests

#968 reimage/delete expired nodes even with the debug_keep_node flag
  src/api-service/__app__/onefuzzlib/workers/nodes.py
Labels: auto-merge, passed-integration-tests

#969 allow updates to a scaleset in the `resize` state
  src/api-service/__app__/scaleset/__init__.py
Labels: auto-merge, passed-integration-tests

#970 handle reimaging failures by resetting reimage_queued
  src/api-service/__app__/onefuzzlib/workers/scalesets.py
Labels: auto-merge, passed-integration-tests

#976 fix service authentication refresh errors
  src/agent/onefuzz-supervisor/src/coordinator.rs
  src/agent/reqwest-retry/src/lib.rs
Labels: passed-integration-tests

#982 add monkeypatch to hotfix pydantic Union issues
  src/pytypes/onefuzztypes/_monkeypatch.py
  src/pytypes/onefuzztypes/events.py
  src/pytypes/onefuzztypes/job_templates.py
  src/pytypes/onefuzztypes/models.py
  src/pytypes/onefuzztypes/requests.py
Labels: auto-merge, passed-integration-tests

#984 Check scaleset size for missing nodes
  src/api-service/__app__/onefuzzlib/workers/scalesets.py
  src/api-service/__app__/timer_workers/__init__.py
Labels: auto-merge, passed-integration-tests

#985 handle serialization of secrets sent from the CLI
  src/cli/onefuzz/backend.py
  src/cli/tests/test_serialize.py
Labels: auto-merge, passed-integration-tests

#987 fix scaleset identity name in the documentation
  docs/AADEntitites.md
Labels: auto-merge

#997 reduce log retention duration to 30 days
  src/deployment/azuredeploy.json
Labels: auto-merge, passed-integration-tests

#1007 normalize log retention
  src/deployment/azuredeploy.json
Labels: auto-merge, passed-integration-tests

#1015 mark tasks as failed when the node is being reimaged due to heartbeat issues
  src/api-service/__app__/onefuzzlib/workers/scalesets.py
Labels: auto-merge, passed-integration-tests

#1017 use the refreshed token when retrying after auth failure
  src/agent/onefuzz-supervisor/src/coordinator.rs
Labels: auto-merge, passed-integration-tests

#1005 remove nodes from db upon reimage
  src/api-service/__app__/onefuzzlib/workers/nodes.py
  src/api-service/__app__/onefuzzlib/workers/scalesets.py
  src/pytypes/onefuzztypes/enums.py
Labels: auto-merge, passed-integration-tests

#1012 update azure-keyvault-secrets to 4.3.0
  src/api-service/__app__/onefuzzlib/secrets.py
  src/api-service/__app__/requirements.txt
Labels: auto-merge, passed-integration-tests

#1011 fix debug report
  src/agent/onefuzz-agent/src/tasks/report/crash_report.rs
  src/cli/onefuzz/debug.py
Labels: auto-merge, passed-integration-tests

#1019 add min_length specifications to Github Issue Template configs
  src/pytypes/onefuzztypes/models.py
Labels: auto-merge, passed-integration-tests

#1029 move to using rustls
  .github/workflows/ci.yml
  src/agent/Cargo.lock
  src/agent/onefuzz-agent/Cargo.toml
  src/agent/onefuzz-supervisor/Cargo.toml
  src/agent/onefuzz-telemetry/Cargo.toml
  src/agent/onefuzz/Cargo.toml
  src/agent/reqwest-retry/Cargo.toml
  src/agent/storage-queue/Cargo.toml
Labels: auto-merge, passed-integration-tests

#1010 instance wide configuration
  docs/webhook_events.md
  src/api-service/__app__/instance_config/__init__.py
  src/api-service/__app__/instance_config/function.json
  src/api-service/__app__/onefuzzlib/config.py
  src/api-service/__app__/onefuzzlib/endpoint_authorization.py
  src/api-service/__app__/pool/__init__.py
  src/api-service/__app__/scaleset/__init__.py
  src/api-service/tests/test_auth_check.py
  src/cli/onefuzz/api.py
  src/deployment/deploy.py
  src/deployment/set_admins.py
  src/pytypes/extra/generate-docs.py
  src/pytypes/onefuzztypes/events.py
  src/pytypes/onefuzztypes/models.py
  src/pytypes/onefuzztypes/requests.py
  src/pytypes/tests/test_instance_config_update.py
Labels: auto-merge, passed-integration-tests
