Repository microsoft/onefuzz, pull requests merged in 2021-07, with the labels that each got.

#922 update azure-cli to 2.25.0
  src/cli/requirements.txt
  src/deployment/deploy.py
  src/deployment/requirements.txt
Labels: auto-merge, passed-integration-tests

#1047 add EventScalesetResizeScheduled
  docs/webhook_events.md
  src/api-service/__app__/onefuzzlib/autoscale.py
  src/api-service/__app__/onefuzzlib/workers/scalesets.py
  src/api-service/__app__/scaleset/__init__.py
  src/pytypes/extra/generate-docs.py
  src/pytypes/onefuzztypes/enums.py
  src/pytypes/onefuzztypes/events.py
Labels: auto-merge, passed-integration-tests

#1050 Pool shrink queue
  src/api-service/__app__/onefuzzlib/workers/nodes.py
  src/api-service/__app__/onefuzzlib/workers/pools.py
  src/api-service/__app__/onefuzzlib/workers/scalesets.py
Labels: auto-merge, passed-integration-tests

#1059 force upgrade custom script extensions
  src/api-service/__app__/onefuzzlib/extension.py
Labels: auto-merge, passed-integration-tests

#1081 increase libfuzzer integration test target_options
  src/integration-tests/integration-test.py
Labels: auto-merge, passed-integration-tests

#1082 Add more information to the logs of transient error
  src/api-service/__app__/onefuzzlib/notifications/ado.py
Labels: auto-merge, passed-integration-tests

#1072 Add `generic_analysis` example that performs coverage analysis
  docs/custom-analysis.md
  src/cli/examples/llvm-source-coverage/.gitignore
  src/cli/examples/llvm-source-coverage/README.md
  src/cli/examples/llvm-source-coverage/inputs/input.txt
  src/cli/examples/llvm-source-coverage/setup/Makefile
  src/cli/examples/llvm-source-coverage/setup/simple.c
  src/cli/examples/llvm-source-coverage/source-coverage-libfuzzer.py
  src/cli/examples/llvm-source-coverage/source-coverage.py
  src/cli/examples/llvm-source-coverage/tools/source-coverage.sh
Labels: auto-merge

#1096 ignore table exists errors from integration testing at the functions layer
  src/integration-tests/integration-test.py
Labels: passed-integration-tests

#1097 verify `{input}` is used by target_env or target_options in coverage task
  src/agent/onefuzz-agent/src/local/coverage.rs
  src/agent/onefuzz-agent/src/tasks/coverage/generic.rs
  src/agent/onefuzz/src/expand.rs
Labels: passed-integration-tests

#1051 automatically clean PII after retention period
  src/api-service/__app__/timer_retention/__init__.py
  src/api-service/__app__/timer_retention/function.json
Labels: auto-merge, passed-integration-tests

#1099 handle azure-mgmt expired auth tokens by clearing the client cache and retrying
  src/api-service/__app__/onefuzzlib/azure/creds.py
  src/api-service/__app__/onefuzzlib/azure/vmss.py
Labels: auto-merge, passed-integration-tests

#1100 relay SignalR integrations through a storage queue
  src/api-service/__app__/onefuzzlib/events.py
  src/api-service/__app__/queue_signalr_events/__init__.py
  src/api-service/__app__/queue_signalr_events/function.json
  src/deployment/deploy.py
Labels: auto-merge, passed-integration-tests

#1104 allow pools & scalesets set to `shutdown` to `halt`
  src/api-service/__app__/onefuzzlib/workers/pools.py
  src/api-service/__app__/onefuzzlib/workers/scalesets.py
Labels: auto-merge, passed-integration-tests

#1105 tasks must use pools not VMs
  src/api-service/__app__/onefuzzlib/tasks/config.py
Labels: auto-merge, passed-integration-tests

#1106 require {input} in target_env or target_options for generator and coverage tasks
  src/api-service/__app__/onefuzzlib/tasks/config.py
  src/api-service/__app__/onefuzzlib/tasks/defs.py
  src/pytypes/onefuzztypes/enums.py
Labels: auto-merge, passed-integration-tests
