Repository microsoft/onefuzz, pull requests merged in 2021-03, with the labels that each got.

#607 update azure-mgmt-resource
  src/api-service/__app__/requirements.txt
Labels: auto-merge, passed-integration-tests

#622 simplify batch-processing log
  src/agent/onefuzz-agent/src/tasks/generic/input_poller.rs
Labels: auto-merge, passed-integration-tests

#612 update azure-mgmt-storage to 17.0.0
  src/api-service/__app__/requirements.txt
  src/utils/add-corpus-storage-accounts/requirements.txt
Labels: auto-merge, passed-integration-tests

#610 update azure-mgmt-eventgrid to 3.0.0rc9
  src/deployment/requirements.txt
  src/utils/add-corpus-storage-accounts/requirements.txt
Labels: auto-merge, passed-integration-tests

#611 update azure-mgmt-compute to 19.0.0
  src/api-service/__app__/requirements.txt
Labels: auto-merge, passed-integration-tests

#623 fix agent `retry` on connection level failures
  src/agent/Cargo.lock
  src/agent/reqwest-retry/Cargo.toml
  src/agent/reqwest-retry/src/lib.rs
Labels: auto-merge, passed-integration-tests

#570 Add symbol cache and filtering
  src/agent/Cargo.lock
  src/agent/coverage/Cargo.toml
  src/agent/coverage/examples/block_coverage.rs
  src/agent/coverage/src/block.rs
  src/agent/coverage/src/block/linux.rs
  src/agent/coverage/src/cache.rs
  src/agent/coverage/src/code.rs
  src/agent/coverage/src/disasm.rs
  src/agent/coverage/src/filter.rs
  src/agent/coverage/src/lib.rs
  src/agent/coverage/src/region.rs
Labels: auto-merge, passed-integration-tests

#621 add node & task heartbeat events
  docs/webhook_events.md
  src/api-service/__app__/queue_node_heartbeat/__init__.py
  src/api-service/__app__/queue_task_heartbeat/__init__.py
  src/pytypes/extra/generate-docs.py
  src/pytypes/onefuzztypes/events.py
Labels: auto-merge, passed-integration-tests

#613 require target_exe to be a canonicalized relative path
  src/api-service/__app__/onefuzzlib/tasks/config.py
Labels: auto-merge, passed-integration-tests

#609 update AFL++ to 3.10c
  src/ci/aflpp.sh
Labels: auto-merge, passed-integration-tests

#625 upgrade azure-storage-blob to 12.8.0
  src/api-service/__app__/onefuzzlib/azure/containers.py
  src/api-service/__app__/requirements.txt
  src/cli/requirements.txt
Labels: auto-merge, passed-integration-tests

#626 update azure-cli and azure-cli-core
  src/cli/requirements.txt
  src/deployment/requirements.txt
Labels: auto-merge, passed-integration-tests

#627 remove pyjwt from dependency list
  src/cli/requirements.txt
Labels: auto-merge, passed-integration-tests

#620 only set VM passwords on Windows
  src/api-service/__app__/onefuzzlib/azure/vm.py
  src/api-service/__app__/onefuzzlib/azure/vmss.py
Labels: auto-merge, passed-integration-tests

#630 re-pin pyjwt version due to conflicts with azure-cli-core
  src/cli/requirements.txt
Labels: auto-merge, passed-integration-tests

#631 add howto guide to understand the libfuzzer_coverage task
  docs/how-to/understand-libfuzzer-coverage.md
Labels: auto-merge, passed-integration-tests

#637 fix markdown link error
  docs/how-to/understand-libfuzzer-coverage.md
Labels: auto-merge, passed-integration-tests

#635 explain the source of task failures related notifications
  src/api-service/__app__/onefuzzlib/notifications/common.py
Labels: auto-merge, passed-integration-tests

#646 Updating Task Heartbeat Struct to actually include job_id
  src/agent/onefuzz-agent/src/tasks/heartbeat.rs
Labels: auto-merge, passed-integration-tests

#649 stop jobs once all tasks are stopped
  src/api-service/__app__/onefuzzlib/jobs.py
  src/api-service/__app__/onefuzzlib/tasks/main.py
Labels: auto-merge, passed-integration-tests

#653 remove azure-mgmt-servicebus from deployment dependencies
  src/deployment/requirements.txt
Labels: auto-merge, passed-integration-tests

#662 Try to demangle symbol names before filtering
  src/agent/Cargo.lock
  src/agent/coverage/Cargo.toml
  src/agent/coverage/src/block/linux.rs
  src/agent/coverage/src/demangle.rs
  src/agent/coverage/src/lib.rs
Labels: auto-merge, passed-integration-tests

#667 fix racy tests for expected failures in web requests
  src/agent/reqwest-retry/src/lib.rs
Labels: passed-integration-tests

#650 mark dependant tasks failed upon failure
  src/api-service/__app__/onefuzzlib/tasks/main.py
Labels: auto-merge, passed-integration-tests

#665 save login details on successful login
  src/cli/onefuzz/backend.py
Labels: auto-merge, passed-integration-tests

#641 Add input file sha256 placeholder
  docs/command-replacements.md
  src/agent/onefuzz/src/expand.rs
  src/agent/onefuzz/src/sha256.rs
Labels: auto-merge, passed-integration-tests

#651 send EventTaskFailed and EventTaskStopped once the task is stopped
  src/api-service/__app__/onefuzzlib/tasks/main.py
Labels: auto-merge, passed-integration-tests

#586 include version and software role to Microsoft collected telemetry
  docs/telemetry.md
  src/agent/onefuzz-telemetry/src/lib.rs
Labels: auto-merge, passed-integration-tests

#671 address issues from by latest regex update
  src/agent/Cargo.lock
  src/agent/onefuzz/src/libfuzzer.rs
Labels: auto-merge, passed-integration-tests

#619 Add salvo telemetry
  docs/telemetry.md
  src/agent/Cargo.lock
  src/agent/onefuzz-telemetry/Cargo.toml
  src/agent/onefuzz-telemetry/src/lib.rs
  src/ci/agent.sh
Labels: auto-merge, passed-integration-tests

#672 handle exception related to manually deleted scalesets
  src/api-service/__app__/onefuzzlib/workers/scalesets.py
Labels: auto-merge, passed-integration-tests

#661 Added UserInfo Filter Logging Function
  src/api-service/__app__/onefuzzlib/events.py
  src/api-service/tests/test_secret_filter.py
Labels: auto-merge, passed-integration-tests

#676 add retry to download_input
  src/agent/onefuzz-agent/src/tasks/utils.rs
Labels: auto-merge, passed-integration-tests

#675 Updated AFL++ to 3.11c.
  src/ci/aflpp.sh
Labels: auto-merge, passed-integration-tests

#680 add setup_dir to the PATH for libfuzzer
  src/agent/onefuzz/src/env.rs
  src/agent/onefuzz/src/lib.rs
  src/agent/onefuzz/src/libfuzzer.rs
Labels: auto-merge, passed-integration-tests

#679 address latest clippy warnings
  src/agent/onefuzz-agent/src/tasks/fuzz/supervisor.rs
  src/agent/onefuzz-agent/src/tasks/generic/input_poller/tests.rs
  src/agent/onefuzz-supervisor/src/buffer.rs
  src/agent/onefuzz/src/libfuzzer.rs
Labels: auto-merge, passed-integration-tests

#682 Add 'setup_dir' to LD_LIBRARY_PATH for unix based libfuzzer targets
  src/agent/onefuzz/src/env.rs
  src/agent/onefuzz/src/input_tester.rs
  src/agent/onefuzz/src/libfuzzer.rs
Labels: auto-merge, passed-integration-tests

#681 libfuzzer library integration tests
  .github/workflows/ci.yml
  src/integration-tests/integration-test.py
  src/integration-tests/libfuzzer-dlopen/Makefile
  src/integration-tests/libfuzzer-dlopen/bad.c
  src/integration-tests/libfuzzer-dlopen/bad.h
  src/integration-tests/libfuzzer-dlopen/main.c
  src/integration-tests/libfuzzer-dlopen/seeds/good.txt
  src/integration-tests/libfuzzer-linked-library/Makefile
  src/integration-tests/libfuzzer-linked-library/Makefile.windows
  src/integration-tests/libfuzzer-linked-library/bad1.c
  src/integration-tests/libfuzzer-linked-library/bad1.h
  src/integration-tests/libfuzzer-linked-library/bad2.c
  src/integration-tests/libfuzzer-linked-library/bad2.h
  src/integration-tests/libfuzzer-linked-library/main.c
  src/integration-tests/libfuzzer-linked-library/seeds/good.txt
Labels: auto-merge, passed-integration-tests

#685 add error message when failing due to pre-existing workset configs
  src/agent/onefuzz-supervisor/src/failure.rs
  src/agent/onefuzz-supervisor/src/main.rs
Labels: auto-merge, passed-integration-tests

#686 Install VC Redistributables
  src/runtime-tools/win64/onefuzz.ps1
  src/runtime-tools/win64/setup.ps1
Labels: auto-merge, passed-integration-tests

#591 provide parsed call stack details asan logs
  src/agent/Cargo.lock
  src/agent/Cargo.toml
  src/agent/libclusterfuzz/.gitignore
  src/agent/libclusterfuzz/Cargo.toml
  src/agent/libclusterfuzz/LICENSE
  src/agent/libclusterfuzz/README.md
  src/agent/libclusterfuzz/src/generated.rs
  src/agent/libclusterfuzz/src/lib.rs
  src/agent/libclusterfuzz/third-party/build.py
  src/agent/libclusterfuzz/third-party/crash_analysis/__init__.py
  src/agent/libclusterfuzz/third-party/crash_analysis/stack_parsing.py
  src/agent/libclusterfuzz/third-party/update.sh
  src/agent/onefuzz-agent/Cargo.toml
  src/agent/onefuzz-agent/src/local/generic_crash_report.rs
  src/agent/onefuzz-agent/src/local/libfuzzer_crash_report.rs
  src/agent/onefuzz-agent/src/tasks/report/crash_report.rs
  src/agent/onefuzz-agent/src/tasks/report/generic.rs
  src/agent/onefuzz-agent/src/tasks/report/libfuzzer_report.rs
  src/agent/onefuzz/Cargo.toml
  src/agent/onefuzz/src/asan.rs
  src/agent/onefuzz/src/expand.rs
  src/agent/onefuzz/src/input_tester.rs
  src/agent/stacktrace-parser/Cargo.toml
  src/agent/stacktrace-parser/data/parsed-traces/asan-check-failure-missing-symbolizer.json
  src/agent/stacktrace-parser/data/parsed-traces/asan-check-failure.json
  src/agent/stacktrace-parser/data/parsed-traces/asan-odr-violation.json
  src/agent/stacktrace-parser/data/parsed-traces/clang-10-asan-breakpoint.json
  src/agent/stacktrace-parser/data/parsed-traces/libfuzzer-asan-log.json
  src/agent/stacktrace-parser/data/parsed-traces/libfuzzer-deadly-signal.json
  src/agent/stacktrace-parser/data/parsed-traces/libfuzzer-linux-llvm10-out-of-memory-malloc.json
  src/agent/stacktrace-parser/data/parsed-traces/libfuzzer-linux-llvm10-out-of-memory-rss.json
  src/agent/stacktrace-parser/data/parsed-traces/libfuzzer-scariness-underflow.json
  src/agent/stacktrace-parser/data/parsed-traces/libfuzzer-scariness.json
  src/agent/stacktrace-parser/data/parsed-traces/libfuzzer-windows-llvm10-out-of-memory-malloc.json
  src/agent/stacktrace-parser/data/parsed-traces/libfuzzer-windows-llvm10-out-of-memory-rss.json
  src/agent/stacktrace-parser/data/parsed-traces/tsan-linux-llvm10-data-race.json
  src/agent/stacktrace-parser/data/stack-traces/asan-check-failure-missing-symbolizer.txt
  src/agent/stacktrace-parser/data/stack-traces/asan-check-failure.txt
  src/agent/stacktrace-parser/data/stack-traces/asan-odr-violation.txt
  src/agent/stacktrace-parser/data/stack-traces/clang-10-asan-breakpoint.txt
  src/agent/stacktrace-parser/data/stack-traces/libfuzzer-asan-log.txt
  src/agent/stacktrace-parser/data/stack-traces/libfuzzer-deadly-signal.txt
  src/agent/stacktrace-parser/data/stack-traces/libfuzzer-linux-llvm10-out-of-memory-malloc.txt
  src/agent/stacktrace-parser/data/stack-traces/libfuzzer-linux-llvm10-out-of-memory-rss.txt
  src/agent/stacktrace-parser/data/stack-traces/libfuzzer-scariness-underflow.txt
  src/agent/stacktrace-parser/data/stack-traces/libfuzzer-scariness.txt
  src/agent/stacktrace-parser/data/stack-traces/libfuzzer-windows-llvm10-out-of-memory-malloc.txt
  src/agent/stacktrace-parser/data/stack-traces/libfuzzer-windows-llvm10-out-of-memory-rss.txt
  src/agent/stacktrace-parser/data/stack-traces/tsan-linux-llvm10-data-race.txt
  src/agent/stacktrace-parser/src/asan.rs
  src/agent/stacktrace-parser/src/bin/parse-stacktrace.rs
  src/agent/stacktrace-parser/src/lib.rs
Labels: auto-merge, passed-integration-tests

#683 simplify config update notification
  src/proxy-manager/src/config.rs
  src/proxy-manager/src/proxy.rs
Labels: auto-merge, passed-integration-tests

#687 update azure-mgmt-network to 18.0.0
  src/api-service/__app__/requirements.txt
Labels: auto-merge, passed-integration-tests

#689 add LoadLibrary-based libfuzzer integration test
  .github/workflows/ci.yml
  src/integration-tests/integration-test.py
  src/integration-tests/libfuzzer-load-library/Makefile
  src/integration-tests/libfuzzer-load-library/bad.c
  src/integration-tests/libfuzzer-load-library/bad.h
  src/integration-tests/libfuzzer-load-library/main.c
  src/integration-tests/libfuzzer-load-library/seeds/good.txt
Labels: auto-merge, passed-integration-tests

#691 add git-bisect howto
  docs/how-to/git-bisect-a-crash.md
Labels: auto-merge

#693 rename salvo telemetry to "upcoming feature"
  docs/telemetry.md
Labels: auto-merge

#696 include the full failure when we give up from retrying
  src/agent/reqwest-retry/src/lib.rs
Labels: auto-merge, passed-integration-tests

#698 update pydantic to 1.8.1
  src/api-service/__app__/requirements.txt
  src/cli/requirements.txt
  src/pytypes/requirements.txt
Labels: auto-merge, passed-integration-tests

#706 add regexes from STACK_FRAME_IGNORE_REGEXES_IF_SYMBOLIZED
  src/agent/libclusterfuzz/src/generated.rs
  src/agent/libclusterfuzz/src/lib.rs
  src/agent/libclusterfuzz/third-party/build.py
Labels: auto-merge, passed-integration-tests

#703 add a single-shot crash report utility
  src/agent/onefuzz-agent/src/local/cmd.rs
  src/agent/onefuzz-agent/src/local/common.rs
  src/agent/onefuzz-agent/src/local/generic_analysis.rs
  src/agent/onefuzz-agent/src/local/generic_crash_report.rs
  src/agent/onefuzz-agent/src/local/generic_generator.rs
  src/agent/onefuzz-agent/src/local/libfuzzer.rs
  src/agent/onefuzz-agent/src/local/libfuzzer_coverage.rs
  src/agent/onefuzz-agent/src/local/libfuzzer_crash_report.rs
  src/agent/onefuzz-agent/src/local/libfuzzer_fuzz.rs
  src/agent/onefuzz-agent/src/local/libfuzzer_merge.rs
  src/agent/onefuzz-agent/src/local/libfuzzer_test_input.rs
  src/agent/onefuzz-agent/src/local/mod.rs
  src/agent/onefuzz-agent/src/local/radamsa.rs
  src/agent/onefuzz-agent/src/local/test_input.rs
  src/agent/onefuzz-agent/src/tasks/report/crash_report.rs
Labels: auto-merge, passed-integration-tests

#709 add second resolution to log timestamp and print to stdout logs
  src/runtime-tools/win64/onefuzz.ps1
Labels: auto-merge, passed-integration-tests

#702 show the full error on proxy loop failure
  src/proxy-manager/src/main.rs
Labels: auto-merge, passed-integration-tests

#711 Fix parsing of list of synced dir
  src/agent/onefuzz-agent/src/local/common.rs
Labels: auto-merge

#704 automatically retry supervisor requests
  src/agent/onefuzz-supervisor/src/coordinator.rs
  src/agent/onefuzz/src/syncdir.rs
  src/agent/onefuzz/src/uploader.rs
  src/agent/reqwest-retry/src/lib.rs
Labels: auto-merge, passed-integration-tests

#714 make asan_log optional in CrashReport
  src/agent/onefuzz-agent/src/tasks/report/crash_report.rs
  src/agent/onefuzz/src/input_tester.rs
  src/agent/stacktrace-parser/src/lib.rs
Labels: auto-merge, passed-integration-tests

#715 expose minimized_stack_depth functionality in the CLI/API
  docs/webhook_events.md
  src/api-service/__app__/onefuzzlib/job_templates/defaults/libfuzzer.py
  src/api-service/__app__/onefuzzlib/tasks/config.py
  src/api-service/__app__/onefuzzlib/tasks/defs.py
  src/cli/onefuzz/api.py
  src/cli/onefuzz/templates/libfuzzer.py
  src/pytypes/onefuzztypes/enums.py
  src/pytypes/onefuzztypes/models.py
Labels: auto-merge, passed-integration-tests

#713 run until end of LLVMFuzzerTestOneInput for collecting coverage
  src/agent/script/win64/libfuzzer-coverage/DumpCounters.js
Labels: auto-merge, passed-integration-tests

#716 work around AAD service principal race condition
  src/deployment/deploy.py
Labels: auto-merge, passed-integration-tests

#725 Removing UserInfo from 'created task' logging
  src/api-service/__app__/onefuzzlib/tasks/main.py
Labels: auto-merge, passed-integration-tests

#724 Removing UserInfo from notifications logging
  src/api-service/__app__/onefuzzlib/notifications/main.py
Labels: auto-merge, passed-integration-tests

#717 hardcode wget to use TLSv1.2
  src/ci/azcopy.sh
Labels: auto-merge, passed-integration-tests

#722 update libclusterfuzz regexes
  src/agent/libclusterfuzz/src/generated.rs
Labels: auto-merge, passed-integration-tests

#721 update azure-cli, azure-cli-core, and msal
  src/cli/requirements.txt
  src/deployment/requirements.txt
Labels: auto-merge, passed-integration-tests

#723 add symbol and module names to StackFrame
  src/agent/debugger/src/dbghelp.rs
  src/agent/debugger/src/stack.rs
  src/agent/onefuzz/src/input_tester.rs
Labels: auto-merge, passed-integration-tests

#732 simplify supervisor failure log code
  src/agent/onefuzz-supervisor/src/failure.rs
Labels: auto-merge, passed-integration-tests

#731 bubble out invalid messages on input queues
  src/agent/onefuzz-agent/src/tasks/analysis/generic.rs
Labels: auto-merge, passed-integration-tests

#749 fix message queue send
  src/agent/storage-queue/src/azure_queue.rs
Labels: auto-merge, passed-integration-tests

#744 add libfuzzer regression tasks to local fuzzing
  src/agent/onefuzz-agent/src/local/cmd.rs
  src/agent/onefuzz-agent/src/local/common.rs
  src/agent/onefuzz-agent/src/local/libfuzzer.rs
  src/agent/onefuzz-agent/src/local/libfuzzer_regression.rs
  src/agent/onefuzz-agent/src/local/mod.rs
  src/agent/onefuzz-agent/src/tasks/regression/common.rs
  src/agent/onefuzz-agent/src/tasks/regression/libfuzzer.rs
Labels: auto-merge, passed-integration-tests

#750 Yield on each enqueue and pop on the local queue
  src/agent/Cargo.lock
  src/agent/storage-queue/Cargo.toml
  src/agent/storage-queue/src/local_queue.rs
Labels: auto-merge, passed-integration-tests

#748 set expect_crash_on_failure default to False on libFuzzer tasks
  src/api-service/__app__/onefuzzlib/job_templates/defaults/libfuzzer.py
  src/cli/onefuzz/templates/libfuzzer.py
Labels: auto-merge, passed-integration-tests

#461 enable using ephemeral disks by default
  docs/webhook_events.md
  src/api-service/__app__/onefuzzlib/autoscale.py
  src/api-service/__app__/onefuzzlib/azure/vmss.py
  src/api-service/__app__/onefuzzlib/workers/scalesets.py
  src/api-service/__app__/scaleset/__init__.py
  src/cli/onefuzz/api.py
  src/pytypes/onefuzztypes/models.py
  src/pytypes/onefuzztypes/requests.py
Labels: auto-merge, passed-integration-tests

#754 remove supervisor-is-done upon test completion
  src/agent/onefuzz-supervisor/src/agent/tests.rs
Labels: auto-merge

#755 use usize for worker_id
  src/agent/onefuzz-agent/src/local/libfuzzer_fuzz.rs
  src/agent/onefuzz-agent/src/tasks/fuzz/libfuzzer_fuzz.rs
  src/agent/onefuzz-telemetry/src/lib.rs
Labels: auto-merge, passed-integration-tests
