Repository microsoft/onefuzz, pull requests merged in 2021-02, with the labels that each got.

#493 add telemetry stats utility
  src/utils/telemetry-stats/.gitignore
  src/utils/telemetry-stats/Cargo.lock
  src/utils/telemetry-stats/Cargo.toml
  src/utils/telemetry-stats/README.md
  src/utils/telemetry-stats/src/main.rs
Labels: auto-merge

#499 update azure-mgmt-compute to 18.2.0
  src/api-service/__app__/requirements.txt
Labels: auto-merge, passed-integration-tests

#503 update pools before nodes or scalesets
  src/api-service/__app__/timer_workers/__init__.py
Labels: auto-merge

#502 Update Proxy heartbeat & logging
  src/agent/onefuzz-telemetry/src/lib.rs
  src/api-service/__app__/onefuzzlib/proxy.py
  src/proxy-manager/Cargo.lock
  src/proxy-manager/Cargo.toml
  src/proxy-manager/src/config.rs
  src/proxy-manager/src/main.rs
  src/pytypes/onefuzztypes/models.py
Labels: auto-merge

#511 Do not update scaleset configs of halting scalesets
  src/api-service/__app__/onefuzzlib/workers/scalesets.py
Labels: auto-merge, passed-integration-tests

#512 update nodes and scalesets in a consistent order
  src/api-service/__app__/timer_workers/__init__.py
Labels: auto-merge, passed-integration-tests

#514 use the primitive types in more places
  src/api-service/__app__/onefuzzlib/azure/creds.py
  src/api-service/__app__/onefuzzlib/tasks/config.py
  src/api-service/__app__/onefuzzlib/tasks/main.py
  src/api-service/__app__/onefuzzlib/workers/nodes.py
  src/cli/examples/oss-fuzz-target.py
  src/cli/onefuzz/api.py
  src/cli/onefuzz/cli.py
  src/cli/onefuzz/debug.py
  src/cli/onefuzz/status/cache.py
  src/cli/onefuzz/templates/__init__.py
  src/cli/onefuzz/templates/afl.py
  src/cli/onefuzz/templates/libfuzzer.py
  src/cli/onefuzz/templates/ossfuzz.py
  src/cli/onefuzz/templates/radamsa.py
  src/pytypes/onefuzztypes/events.py
  src/pytypes/onefuzztypes/models.py
  src/pytypes/onefuzztypes/requests.py
Labels: passed-integration-tests

#516 standardize on unix file endings
  contrib/deploy-onefuzz-via-azure-devops/README.md
  src/api-service/__app__/negotiate/__init__.py
  src/api-service/tests/__init__.py
  src/api-service/tests/test_autoscale.py
  src/api-service/tests/test_scheduler.py
  src/api-service/tests/test_webhook_hmac.py
  src/cli/examples/azure-functions-example/info/__init__.py
Labels: auto-merge

#530 Fix wait_for_running for templates
  src/cli/onefuzz/templates/__init__.py
  src/pytypes/onefuzztypes/enums.py
Labels: auto-merge, passed-integration-tests

#527 add roles to agent & supervisor
  src/agent/onefuzz-agent/src/tasks/config.rs
  src/agent/onefuzz-supervisor/src/main.rs
  src/agent/onefuzz-telemetry/src/lib.rs
Labels: auto-merge, passed-integration-tests

#532 Enable waiting for a job to start for managed templates
  src/cli/onefuzz/job_templates/builder.py
  src/cli/onefuzz/job_templates/handlers.py
  src/cli/onefuzz/job_templates/job_monitor.py
  src/cli/onefuzz/templates/__init__.py
Labels: auto-merge, passed-integration-tests

#537 report the total coverage after processing all inputs in local mode
  src/agent/onefuzz-agent/src/tasks/coverage/libfuzzer_coverage.rs
Labels: auto-merge, passed-integration-tests

#554 make missing symbols for coverage tasks more explicit
  src/agent/onefuzz-agent/src/tasks/coverage/recorder.rs
Labels: auto-merge, passed-integration-tests

#564 add .gitignore to ignore libfuzzer-dotnet build artifacts
  src/integration-tests/libfuzzer-dotnet/.gitignore
Labels: auto-merge

#568 clarify scaleset logging
  src/api-service/__app__/onefuzzlib/workers/scalesets.py
Labels: auto-merge, passed-integration-tests

#577 add instance information to webhooks
  docs/webhook_events.md
  src/api-service/__app__/onefuzzlib/events.py
  src/api-service/__app__/onefuzzlib/webhooks.py
  src/api-service/tests/test_webhook_hmac.py
  src/pytypes/extra/generate-docs.py
  src/pytypes/onefuzztypes/events.py
Labels: auto-merge, passed-integration-tests

#565 stop jobs that do not start within 30 days
  src/api-service/__app__/onefuzzlib/jobs.py
  src/api-service/__app__/timer_tasks/__init__.py
Labels: auto-merge, passed-integration-tests

#552 update proxy port ranges to avoid current blocks
  src/api-service/__app__/onefuzzlib/proxy_forward.py
Labels: auto-merge, passed-integration-tests

#567 allow nodes with multiple tasks to continue on task stop
  src/api-service/__app__/onefuzzlib/workers/nodes.py
  src/api-service/__app__/timer_workers/__init__.py
Labels: auto-merge, passed-integration-tests

#582 handle error condition when creating a container that is being deleted
  src/api-service/__app__/onefuzzlib/azure/containers.py
Labels: auto-merge, passed-integration-tests

#584 release 2.6.0
  CHANGELOG.md
  CURRENT_VERSION
Labels: passed-integration-tests

#595 update jinja2
  src/api-service/__app__/requirements.txt
Labels: passed-integration-tests

#598 add `onefuzz containers files download_dir`
  src/cli/onefuzz/api.py
  src/cli/onefuzz/azcopy.py
  src/cli/onefuzz/backend.py
  src/cli/onefuzz/debug.py
  src/cli/onefuzz/templates/__init__.py
Labels: auto-merge, passed-integration-tests

#597 fix bool queries
  src/api-service/__app__/onefuzzlib/orm.py
Labels: auto-merge, passed-integration-tests

#587 Renames application insights keys to be more clear
  docs/telemetry.md
  src/agent/Cargo.lock
  src/agent/onefuzz-agent/src/local/common.rs
  src/agent/onefuzz-agent/src/managed/cmd.rs
  src/agent/onefuzz-agent/src/tasks/config.rs
  src/agent/onefuzz-supervisor/src/config.rs
  src/agent/onefuzz-supervisor/src/main.rs
  src/agent/onefuzz-telemetry/Cargo.toml
  src/agent/onefuzz-telemetry/src/lib.rs
  src/agent/onefuzz/src/lib.rs
  src/proxy-manager/Cargo.lock
  src/proxy-manager/src/config.rs
Labels: auto-merge, passed-integration-tests

#594 Update Task Heartbeat to include Job_id
  src/agent/onefuzz-agent/src/tasks/config.rs
  src/agent/onefuzz-agent/src/tasks/heartbeat.rs
  src/api-service/__app__/queue_task_heartbeat/__init__.py
  src/pytypes/onefuzztypes/models.py
Labels: auto-merge, passed-integration-tests

#588 Actively tail worker stdio from supervisor agent
  src/agent/onefuzz-supervisor/src/buffer.rs
  src/agent/onefuzz-supervisor/src/main.rs
  src/agent/onefuzz-supervisor/src/worker.rs
  src/agent/onefuzz-supervisor/src/worker/tests.rs
Labels: auto-merge, passed-integration-tests

#561 Update command variable expansion
  docs/command-replacements.md
  src/agent/onefuzz-agent/src/tasks/analysis/generic.rs
  src/agent/onefuzz-agent/src/tasks/fuzz/generator.rs
  src/agent/onefuzz-agent/src/tasks/fuzz/supervisor.rs
  src/agent/onefuzz-agent/src/tasks/merge/generic.rs
  src/agent/onefuzz/src/expand.rs
Labels: auto-merge, passed-integration-tests

#599 remove azure-mgmt-web from prereq deployments
  src/deployment/requirements.txt
Labels: auto-merge, passed-integration-tests

#601 add context to logging of supervisor work queue interaction
  src/agent/onefuzz-supervisor/src/agent.rs
  src/agent/onefuzz-supervisor/src/work.rs
  src/agent/storage-queue/src/lib.rs
Labels: passed-integration-tests

#604 Release 2.7.0
  CHANGELOG.md
  CURRENT_VERSION
Labels: auto-merge
