Repository microsoft/onefuzz, pull requests merged in 2021-05, with the labels that each got.

#861 update azure-cli and azure-cli-core to 2.23.0
  src/deployment/requirements.txt
Labels: auto-merge, passed-integration-tests

#879 log full error context when supervisor exits
  src/agent/onefuzz-supervisor/src/main.rs
Labels: auto-merge, passed-integration-tests

#882 add event for scaleset state updates
  docs/webhook_events.md
  src/api-service/__app__/onefuzzlib/autoscale.py
  src/api-service/__app__/onefuzzlib/workers/pools.py
  src/api-service/__app__/onefuzzlib/workers/scalesets.py
  src/api-service/__app__/scaleset/__init__.py
  src/pytypes/extra/generate-docs.py
  src/pytypes/onefuzztypes/events.py
Labels: auto-merge, passed-integration-tests

#881 update HasState Protocol to alway log state transitions
  src/api-service/__app__/onefuzzlib/orm.py
Labels: auto-merge, passed-integration-tests

#887 only run CodeQL on `main`
  .github/workflows/codeql-analysis.yml
Labels: auto-merge

#883 force ASCII generation of markdown document generation
  src/ci/onefuzztypes.sh
  src/pytypes/extra/generate-docs.py
Labels: auto-merge

#885 update azure-identity to 1.6.0
  src/api-service/__app__/requirements.txt
Labels: auto-merge, passed-integration-tests

#886 update azure-mgmt-resource to 17.0.0
  src/api-service/__app__/requirements.txt
Labels: auto-merge, passed-integration-tests

#889 upgrade azure-core to 1.14.0
  src/api-service/__app__/requirements.txt
Labels: auto-merge, passed-integration-tests

#892 Remove transitive `async-std` dep
  src/agent/Cargo.lock
  src/agent/onefuzz-agent/Cargo.toml
  src/agent/onefuzz/Cargo.toml
  src/agent/reqwest-retry/Cargo.toml
  src/agent/storage-queue/Cargo.toml
Labels: auto-merge, passed-integration-tests

#896 Azure AD entities description
  docs/AADEntitites.md
Labels: auto-merge

#872 Single tenant auth, issuer url fix
  src/deployment/deploy.py
Labels: auto-merge, passed-integration-tests

#878 use azcopy for upload_dir
  src/cli/onefuzz/azcopy.py
  src/cli/onefuzz/backend.py
Labels: auto-merge, passed-integration-tests

#890 update azure-mgmt-storage to 18.0.0
  src/api-service/__app__/requirements.txt
  src/utils/add-corpus-storage-accounts/requirements.txt
Labels: auto-merge, passed-integration-tests

#898 fix deployment using client_id
  src/deployment/deploy.py
Labels: passed-integration-tests

#894 Use assign User.Read from Microsoft graph instead of AAD Graph
  src/deployment/deploy.py
Labels: auto-merge, passed-integration-tests

#801 Stop tasks on nodes before deleting task queues
  src/api-service/__app__/onefuzzlib/agent_events.py
  src/api-service/__app__/onefuzzlib/tasks/main.py
  src/api-service/__app__/onefuzzlib/workers/nodes.py
Labels: auto-merge, passed-integration-tests

#900 Add setup arguments to enable specifying alt tenants on the CLI
  src/cli/onefuzz/api.py
Labels: auto-merge, passed-integration-tests

#901 add setup_dir to generator task
  docs/command-replacements.md
  src/agent/onefuzz-agent/src/tasks/fuzz/generator.rs
Labels: auto-merge, passed-integration-tests

#839 Refactoring proxy lifetime to only shutdown when proxy is out-of-date.
  docs/webhook_events.md
  src/api-service/__app__/onefuzzlib/extension.py
  src/api-service/__app__/onefuzzlib/proxy.py
  src/api-service/__app__/onefuzzlib/proxy_forward.py
  src/api-service/__app__/onefuzzlib/tasks/main.py
  src/api-service/__app__/proxy/__init__.py
  src/api-service/__app__/queue_proxy_update/__init__.py
  src/api-service/__app__/timer_daily/__init__.py
  src/ci/api-service-toolcheck.sh
  src/proxy-manager/src/config.rs
  src/pytypes/extra/generate-docs.py
  src/pytypes/onefuzztypes/events.py
  src/pytypes/onefuzztypes/models.py
Labels: auto-merge, passed-integration-tests

#907 encode proxy name as base58 to allow full deletion of resources
  src/api-service/__app__/onefuzzlib/azure/vm.py
  src/api-service/__app__/onefuzzlib/proxy.py
  src/api-service/__app__/requirements.txt
Labels: auto-merge, passed-integration-tests

#909 Fix multi proxy race condition
  src/api-service/__app__/onefuzzlib/proxy.py
  src/api-service/__app__/timer_daily/__init__.py
  src/api-service/__app__/timer_proxy/__init__.py
Labels: auto-merge, passed-integration-tests

#911 Catch argparse type errors
  src/cli/onefuzz/cli.py
Labels: auto-merge

#903 update azure-mgmt-resource to 18.0.0
  src/api-service/__app__/onefuzzlib/azure/creds.py
  src/api-service/__app__/requirements.txt
Labels: auto-merge, passed-integration-tests

#905 basic list proxy functionality
  src/api-service/__app__/proxy/__init__.py
  src/cli/onefuzz/api.py
  src/pytypes/onefuzztypes/requests.py
  src/pytypes/onefuzztypes/responses.py
Labels: auto-merge, passed-integration-tests

#928 only set the SSH key permissions on Windows once
  src/agent/onefuzz-supervisor/src/commands.rs
Labels: auto-merge, passed-integration-tests

#926 Rename helper method for setup-relative files
  src/cli/examples/domato.py
  src/cli/examples/honggfuzz.py
  src/cli/onefuzz/templates/__init__.py
  src/cli/onefuzz/templates/afl.py
  src/cli/onefuzz/templates/libfuzzer.py
  src/cli/onefuzz/templates/ossfuzz.py
  src/cli/onefuzz/templates/radamsa.py
  src/cli/onefuzz/templates/regression.py
  src/cli/tests/test_template_helper.py
Labels: auto-merge

#929 Add timeout when recording Linux coverage
  src/agent/coverage/examples/coverage.rs
  src/agent/coverage/src/block/linux.rs
Labels: auto-merge
