Repository microsoft/onefuzz, pull requests merged in 2021-01, with the labels that each got.

#378 Verify a workset only exists along with a reboot context
  src/agent/onefuzz-supervisor/src/main.rs
  src/agent/onefuzz-supervisor/src/reboot.rs
  src/agent/onefuzz-supervisor/src/setup.rs
  src/agent/onefuzz-supervisor/src/work.rs
  src/integration-tests/integration-test.py
Labels: auto-merge, passed-integration-tests

#387 add delayed start to heartbeats
  src/agent/onefuzz/src/heartbeat.rs
  src/agent/onefuzz/src/jitter.rs
Labels: auto-merge, passed-integration-tests

#390 Re-add windows ssh key
  src/api-service/__app__/onefuzzlib/extension.py
  src/api-service/__app__/onefuzzlib/pools.py
  src/runtime-tools/linux/setup.sh
  src/runtime-tools/win64/setup.ps1
Labels: auto-merge, passed-integration-tests

#391 filter out deleted nodes as to prevent them from being saved later
  src/api-service/__app__/onefuzzlib/pools.py
Labels: auto-merge, passed-integration-tests

#401 add 'onefuzz debug log tail'
  src/cli/onefuzz/debug.py
Labels: auto-merge, passed-integration-tests

#400 log stdout & stderr lines for supervisor & generator
  src/agent/onefuzz-agent/src/tasks/fuzz/generator.rs
  src/agent/onefuzz-agent/src/tasks/fuzz/supervisor.rs
  src/agent/onefuzz/src/process.rs
Labels: auto-merge, passed-integration-tests

#410 address clippy issues in proxy-manager
  src/proxy-manager/src/proxy.rs
Labels: auto-merge, passed-integration-tests

#403 Fixes race condition of a libfuzzer coverage without inputs
  src/agent/onefuzz-agent/src/tasks/coverage/libfuzzer_coverage.rs
Labels: auto-merge, bug, passed-integration-tests

#393 upgrade AFL++ to 3.00b
  src/ci/aflpp.sh
Labels: auto-merge, passed-integration-tests

#384 increase function timeout to 15 minutes
  src/api-service/__app__/host.json
Labels: auto-merge, passed-integration-tests

#412 Re-adds POST for node endpoint
  src/api-service/__app__/node/__init__.py
  src/api-service/__app__/node/function.json
Labels: auto-merge, passed-integration-tests

#395 lint development utilities
  src/integration-tests/integration-test.py
  src/utils/ado-testing/check-ado.py
  src/utils/ado-testing/check-notifications.py
Labels: auto-merge, passed-integration-tests

#381 handle libfuzzer fuzzing non-zero exits better
  docs/webhook_events.md
  src/agent/onefuzz-agent/src/debug/libfuzzer_coverage.rs
  src/agent/onefuzz-agent/src/debug/libfuzzer_crash_report.rs
  src/agent/onefuzz-agent/src/debug/libfuzzer_fuzz.rs
  src/agent/onefuzz-agent/src/debug/libfuzzer_merge.rs
  src/agent/onefuzz-agent/src/tasks/coverage/libfuzzer_coverage.rs
  src/agent/onefuzz-agent/src/tasks/fuzz/generator.rs
  src/agent/onefuzz-agent/src/tasks/fuzz/libfuzzer_fuzz.rs
  src/agent/onefuzz-agent/src/tasks/merge/libfuzzer_merge.rs
  src/agent/onefuzz-agent/src/tasks/report/generic.rs
  src/agent/onefuzz-agent/src/tasks/report/libfuzzer_report.rs
  src/agent/onefuzz-agent/src/tasks/utils.rs
  src/agent/onefuzz/src/libfuzzer.rs
  src/api-service/__app__/onefuzzlib/job_templates/defaults/libfuzzer.py
  src/api-service/__app__/onefuzzlib/tasks/config.py
  src/api-service/__app__/onefuzzlib/tasks/defs.py
  src/cli/onefuzz/api.py
  src/cli/onefuzz/templates/libfuzzer.py
  src/pytypes/onefuzztypes/enums.py
  src/pytypes/onefuzztypes/models.py
Labels: auto-merge, passed-integration-tests

#409 Address clippy issues
  src/agent/Cargo.lock
  src/agent/coverage/src/block/linux.rs
  src/agent/onefuzz-agent/build.rs
  src/agent/onefuzz-agent/src/debug/libfuzzer_merge.rs
  src/agent/onefuzz-agent/src/tasks/fuzz/generator.rs
  src/agent/onefuzz-agent/src/tasks/fuzz/supervisor.rs
  src/agent/onefuzz-agent/src/tasks/generic/input_poller/tests.rs
  src/agent/onefuzz-agent/src/tasks/merge/generic.rs
  src/agent/onefuzz-agent/src/tasks/merge/libfuzzer_merge.rs
  src/agent/onefuzz-agent/src/tasks/report/crash_report.rs
  src/agent/onefuzz-supervisor/build.rs
  src/agent/onefuzz-supervisor/src/config.rs
  src/agent/onefuzz-supervisor/src/coordinator.rs
  src/agent/onefuzz-supervisor/src/main.rs
  src/agent/onefuzz-supervisor/src/worker.rs
  src/agent/onefuzz-supervisor/src/worker/tests.rs
  src/agent/onefuzz/src/asan.rs
  src/agent/onefuzz/src/fs.rs
  src/agent/onefuzz/src/libfuzzer.rs
  src/agent/onefuzz/src/telemetry.rs
  src/agent/onefuzz/src/triage.rs
  src/agent/reqwest-retry/Cargo.toml
Labels: auto-merge, passed-integration-tests

#404 restrict api endpoints
  src/api-service/__app__/agent_can_schedule/__init__.py
  src/api-service/__app__/agent_commands/__init__.py
  src/api-service/__app__/agent_events/__init__.py
  src/api-service/__app__/agent_registration/__init__.py
  src/api-service/__app__/containers/__init__.py
  src/api-service/__app__/download/__init__.py
  src/api-service/__app__/job_templates/__init__.py
  src/api-service/__app__/job_templates_manage/__init__.py
  src/api-service/__app__/jobs/__init__.py
  src/api-service/__app__/node/__init__.py
  src/api-service/__app__/notifications/__init__.py
  src/api-service/__app__/onefuzzlib/endpoint_authorization.py
  src/api-service/__app__/pool/__init__.py
  src/api-service/__app__/proxy/__init__.py
  src/api-service/__app__/repro_vms/__init__.py
  src/api-service/__app__/scaleset/__init__.py
  src/api-service/__app__/tasks/__init__.py
  src/api-service/__app__/webhooks/__init__.py
  src/api-service/__app__/webhooks_logs/__init__.py
  src/api-service/__app__/webhooks_ping/__init__.py
Labels: auto-merge, passed-integration-tests

#397 limit updating outdated nodes to 500 at a time
  src/api-service/__app__/onefuzzlib/pools.py
Labels: auto-merge, passed-integration-tests

#346 Multi-tenant authentication support in CLI
  src/cli/onefuzz/api.py
  src/cli/onefuzz/backend.py
Labels: auto-merge, passed-integration-tests

#402 Colocate tasks
  docs/webhook_events.md
  src/api-service/__app__/onefuzzlib/agent_events.py
  src/api-service/__app__/onefuzzlib/job_templates/defaults/libfuzzer.py
  src/api-service/__app__/onefuzzlib/tasks/main.py
  src/api-service/__app__/onefuzzlib/tasks/scheduler.py
  src/api-service/tests/test_scheduler.py
  src/cli/onefuzz/api.py
  src/cli/onefuzz/templates/libfuzzer.py
  src/pytypes/onefuzztypes/models.py
Labels: auto-merge, passed-integration-tests

#399 update devops prereq
  src/api-service/__app__/requirements.txt
Labels: auto-merge, passed-integration-tests

#411 Add ssh keys to nodes on demand
  src/agent/Cargo.lock
  src/agent/onefuzz-supervisor/Cargo.toml
  src/agent/onefuzz-supervisor/src/agent.rs
  src/agent/onefuzz-supervisor/src/commands.rs
  src/agent/onefuzz-supervisor/src/coordinator.rs
  src/agent/onefuzz-supervisor/src/coordinator/double.rs
  src/agent/onefuzz-supervisor/src/main.rs
  src/agent/onefuzz-supervisor/src/scheduler.rs
  src/api-service/__app__/node_add_ssh_key/__init__.py
  src/api-service/__app__/node_add_ssh_key/function.json
  src/api-service/__app__/onefuzzlib/pools.py
  src/cli/onefuzz/api.py
  src/pytypes/onefuzztypes/models.py
  src/pytypes/onefuzztypes/requests.py
Labels: auto-merge, passed-integration-tests

#334 support multiple corpus accounts
  src/api-service/__app__/agent_registration/__init__.py
  src/api-service/__app__/containers/__init__.py
  src/api-service/__app__/download/__init__.py
  src/api-service/__app__/onefuzzlib/azure/containers.py
  src/api-service/__app__/onefuzzlib/azure/creds.py
  src/api-service/__app__/onefuzzlib/azure/queue.py
  src/api-service/__app__/onefuzzlib/azure/storage.py
  src/api-service/__app__/onefuzzlib/azure/table.py
  src/api-service/__app__/onefuzzlib/extension.py
  src/api-service/__app__/onefuzzlib/notifications/ado.py
  src/api-service/__app__/onefuzzlib/notifications/common.py
  src/api-service/__app__/onefuzzlib/notifications/github_issues.py
  src/api-service/__app__/onefuzzlib/notifications/main.py
  src/api-service/__app__/onefuzzlib/notifications/teams.py
  src/api-service/__app__/onefuzzlib/pools.py
  src/api-service/__app__/onefuzzlib/proxy.py
  src/api-service/__app__/onefuzzlib/reports.py
  src/api-service/__app__/onefuzzlib/repro.py
  src/api-service/__app__/onefuzzlib/tasks/config.py
  src/api-service/__app__/onefuzzlib/tasks/main.py
  src/api-service/__app__/onefuzzlib/tasks/scheduler.py
  src/api-service/__app__/onefuzzlib/updates.py
  src/api-service/__app__/onefuzzlib/webhooks.py
  src/api-service/__app__/pool/__init__.py
  src/api-service/__app__/queue_file_changes/__init__.py
  src/deployment/azuredeploy.json
  src/utils/add-corpus-storage-accounts/add-corpus-storage-account.py
  src/utils/add-corpus-storage-accounts/requirements-lint.txt
  src/utils/add-corpus-storage-accounts/requirements.txt
Labels: auto-merge, passed-integration-tests

#416 Shorten the expiry window for the work queue SAS URLs assigned at node registration
  src/agent/onefuzz-supervisor/src/config.rs
  src/agent/onefuzz-supervisor/src/work.rs
  src/agent/onefuzz/src/http.rs
  src/api-service/__app__/agent_registration/__init__.py
  src/api-service/__app__/onefuzzlib/azure/queue.py
Labels: auto-merge, passed-integration-tests

#418 compare containers rather than SAS urls when building worksets
  src/api-service/__app__/onefuzzlib/tasks/scheduler.py
Labels: auto-merge, bug, passed-integration-tests

#419 Clear node messages on deletion
  src/api-service/__app__/onefuzzlib/pools.py
Labels: auto-merge, passed-integration-tests

#423 add context to all fs calls
  src/agent/onefuzz-agent/src/tasks/coverage/libfuzzer_coverage.rs
  src/agent/onefuzz-agent/src/tasks/coverage/recorder.rs
  src/agent/onefuzz-agent/src/tasks/fuzz/libfuzzer_fuzz.rs
  src/agent/onefuzz-agent/src/tasks/stats/afl.rs
  src/agent/onefuzz-supervisor/src/config.rs
  src/agent/onefuzz-supervisor/src/done.rs
  src/agent/onefuzz-supervisor/src/reboot.rs
  src/agent/onefuzz-supervisor/src/setup.rs
  src/agent/onefuzz-supervisor/src/work.rs
  src/agent/onefuzz-supervisor/src/worker.rs
  src/agent/onefuzz/src/fs.rs
  src/agent/onefuzz/src/machine_id.rs
  src/agent/onefuzz/src/sha256.rs
  src/agent/onefuzz/src/syncdir.rs
Labels: auto-merge, passed-integration-tests

#394 Unify Dashboard & Webhook events
  docs/webhook_events.md
  src/api-service/__app__/agent_registration/__init__.py
  src/api-service/__app__/onefuzzlib/agent_events.py
  src/api-service/__app__/onefuzzlib/autoscale.py
  src/api-service/__app__/onefuzzlib/dashboard.py
  src/api-service/__app__/onefuzzlib/events.py
  src/api-service/__app__/onefuzzlib/jobs.py
  src/api-service/__app__/onefuzzlib/notifications/main.py
  src/api-service/__app__/onefuzzlib/orm.py
  src/api-service/__app__/onefuzzlib/pools.py
  src/api-service/__app__/onefuzzlib/proxy.py
  src/api-service/__app__/onefuzzlib/reports.py
  src/api-service/__app__/onefuzzlib/tasks/main.py
  src/api-service/__app__/onefuzzlib/tasks/scheduler.py
  src/api-service/__app__/onefuzzlib/webhooks.py
  src/api-service/__app__/pool/__init__.py
  src/api-service/__app__/proxy_notification/__init__.py
  src/api-service/__app__/queue_file_changes/__init__.py
  src/api-service/__app__/queue_node_heartbeat/__init__.py
  src/api-service/__app__/queue_task_heartbeat/__init__.py
  src/api-service/__app__/queue_updates/__init__.py
  src/api-service/__app__/scaleset/__init__.py
  src/api-service/__app__/timer_proxy/__init__.py
  src/api-service/__app__/timer_repro/__init__.py
  src/api-service/__app__/timer_tasks/__init__.py
  src/api-service/__app__/timer_workers/__init__.py
  src/api-service/tests/test_webhook_hmac.py
  src/cli/onefuzz/api.py
  src/cli/onefuzz/status/cache.py
  src/cli/onefuzz/status/signalr.py
  src/cli/onefuzz/status/top.py
  src/cli/onefuzz/status/top_view.py
  src/pytypes/extra/generate-docs.py
  src/pytypes/onefuzztypes/enums.py
  src/pytypes/onefuzztypes/events.py
  src/pytypes/onefuzztypes/requests.py
  src/pytypes/onefuzztypes/webhooks.py
Labels: auto-merge, breaking-change, passed-integration-tests

#426 update MSAL to 1.8.0
  src/cli/requirements.txt
Labels: auto-merge, passed-integration-tests

#428 Switch to `memmap2`
  src/agent/Cargo.lock
  src/agent/coverage/Cargo.toml
  src/agent/coverage/src/pe.rs
  src/agent/debugger/Cargo.toml
  src/agent/debugger/src/target.rs
  src/ci/agent.sh
Labels: auto-merge, passed-integration-tests

#422 Fix condition for triggering new unique report event
  src/agent/onefuzz-agent/src/tasks/report/crash_report.rs
Labels: auto-merge, passed-integration-tests

#417 adding {setup_dir} to variable expansion
  docs/command-replacements.md
  src/agent/onefuzz-agent/src/debug/generic_crash_report.rs
  src/agent/onefuzz-agent/src/debug/libfuzzer_coverage.rs
  src/agent/onefuzz-agent/src/debug/libfuzzer_crash_report.rs
  src/agent/onefuzz-agent/src/debug/libfuzzer_fuzz.rs
  src/agent/onefuzz-agent/src/debug/libfuzzer_merge.rs
  src/agent/onefuzz-agent/src/main.rs
  src/agent/onefuzz-agent/src/tasks/analysis/generic.rs
  src/agent/onefuzz-agent/src/tasks/config.rs
  src/agent/onefuzz-agent/src/tasks/coverage/libfuzzer_coverage.rs
  src/agent/onefuzz-agent/src/tasks/fuzz/generator.rs
  src/agent/onefuzz-agent/src/tasks/fuzz/libfuzzer_fuzz.rs
  src/agent/onefuzz-agent/src/tasks/fuzz/supervisor.rs
  src/agent/onefuzz-agent/src/tasks/merge/generic.rs
  src/agent/onefuzz-agent/src/tasks/merge/libfuzzer_merge.rs
  src/agent/onefuzz-agent/src/tasks/report/generic.rs
  src/agent/onefuzz-agent/src/tasks/report/libfuzzer_report.rs
  src/agent/onefuzz-supervisor/src/debug.rs
  src/agent/onefuzz-supervisor/src/scheduler.rs
  src/agent/onefuzz-supervisor/src/setup.rs
  src/agent/onefuzz-supervisor/src/work.rs
  src/agent/onefuzz-supervisor/src/worker.rs
  src/agent/onefuzz-supervisor/src/worker/double.rs
  src/agent/onefuzz-supervisor/src/worker/tests.rs
  src/agent/onefuzz/src/expand.rs
  src/agent/onefuzz/src/input_tester.rs
  src/agent/onefuzz/src/libfuzzer.rs
Labels: auto-merge, passed-integration-tests

#429 Update Linux tracer version
  src/agent/Cargo.lock
  src/agent/coverage/Cargo.toml
  src/agent/coverage/src/block/linux.rs
  src/agent/onefuzz/Cargo.toml
  src/agent/onefuzz/src/input_tester.rs
  src/agent/onefuzz/src/triage.rs
Labels: auto-merge, passed-integration-tests

#435 Add missing prerequisites to the Getting Started guide
  docs/getting-started.md
Labels: auto-merge

#436 verify local debugger installs before launching repro
  src/integration-tests/integration-test.py
Labels: auto-merge, passed-integration-tests

#405 experimental "local fuzzing" support
  src/agent/onefuzz-agent/src/debug/cmd.rs
  src/agent/onefuzz-agent/src/debug/generic_crash_report.rs
  src/agent/onefuzz-agent/src/debug/libfuzzer_coverage.rs
  src/agent/onefuzz-agent/src/debug/libfuzzer_crash_report.rs
  src/agent/onefuzz-agent/src/debug/libfuzzer_fuzz.rs
  src/agent/onefuzz-agent/src/debug/libfuzzer_merge.rs
  src/agent/onefuzz-agent/src/debug/mod.rs
  src/agent/onefuzz-agent/src/local/cmd.rs
  src/agent/onefuzz-agent/src/local/common.rs
  src/agent/onefuzz-agent/src/local/generic_crash_report.rs
  src/agent/onefuzz-agent/src/local/generic_generator.rs
  src/agent/onefuzz-agent/src/local/libfuzzer.rs
  src/agent/onefuzz-agent/src/local/libfuzzer_coverage.rs
  src/agent/onefuzz-agent/src/local/libfuzzer_crash_report.rs
  src/agent/onefuzz-agent/src/local/libfuzzer_fuzz.rs
  src/agent/onefuzz-agent/src/local/mod.rs
  src/agent/onefuzz-agent/src/local/radamsa.rs
  src/agent/onefuzz-agent/src/main.rs
  src/agent/onefuzz-agent/src/managed/cmd.rs
  src/agent/onefuzz-agent/src/managed/mod.rs
  src/agent/onefuzz-agent/src/tasks/analysis/generic.rs
  src/agent/onefuzz-agent/src/tasks/config.rs
  src/agent/onefuzz-agent/src/tasks/coverage/libfuzzer_coverage.rs
  src/agent/onefuzz-agent/src/tasks/fuzz/generator.rs
  src/agent/onefuzz-agent/src/tasks/fuzz/libfuzzer_fuzz.rs
  src/agent/onefuzz-agent/src/tasks/generic/input_poller.rs
  src/agent/onefuzz-agent/src/tasks/generic/input_poller/callback.rs
  src/agent/onefuzz-agent/src/tasks/generic/input_poller/tests.rs
  src/agent/onefuzz-agent/src/tasks/report/crash_report.rs
  src/agent/onefuzz-agent/src/tasks/report/generic.rs
  src/agent/onefuzz-agent/src/tasks/report/libfuzzer_report.rs
  src/agent/onefuzz-supervisor/src/worker.rs
  src/agent/onefuzz/src/libfuzzer.rs
  src/agent/onefuzz/src/syncdir.rs
  src/agent/onefuzz/src/telemetry.rs
  src/api-service/__app__/onefuzzlib/tasks/scheduler.py
Labels: auto-merge, passed-integration-tests

#444 add expanding {tools_dir} to supervisor_options and supervisor_env
  src/agent/onefuzz-agent/src/tasks/fuzz/supervisor.rs
Labels: auto-merge, passed-integration-tests

#445 always set SignalR events at the end of handlers
  src/api-service/__app__/agent_can_schedule/__init__.py
  src/api-service/__app__/agent_can_schedule/function.json
  src/api-service/__app__/agent_commands/__init__.py
  src/api-service/__app__/agent_commands/function.json
  src/api-service/__app__/agent_events/__init__.py
  src/api-service/__app__/agent_events/function.json
  src/api-service/__app__/agent_registration/__init__.py
  src/api-service/__app__/agent_registration/function.json
  src/api-service/__app__/containers/__init__.py
  src/api-service/__app__/containers/function.json
  src/api-service/__app__/download/__init__.py
  src/api-service/__app__/download/function.json
  src/api-service/__app__/info/__init__.py
  src/api-service/__app__/info/function.json
  src/api-service/__app__/job_templates/__init__.py
  src/api-service/__app__/job_templates/function.json
  src/api-service/__app__/job_templates_manage/__init__.py
  src/api-service/__app__/job_templates_manage/function.json
  src/api-service/__app__/jobs/__init__.py
  src/api-service/__app__/jobs/function.json
  src/api-service/__app__/negotiate/function.json
  src/api-service/__app__/node/__init__.py
  src/api-service/__app__/node/function.json
  src/api-service/__app__/node_add_ssh_key/__init__.py
  src/api-service/__app__/node_add_ssh_key/function.json
  src/api-service/__app__/notifications/__init__.py
  src/api-service/__app__/notifications/function.json
  src/api-service/__app__/pool/__init__.py
  src/api-service/__app__/pool/function.json
  src/api-service/__app__/proxy/__init__.py
  src/api-service/__app__/proxy/function.json
  src/api-service/__app__/proxy_notification/function.json
  src/api-service/__app__/queue_file_changes/function.json
  src/api-service/__app__/queue_node_heartbeat/function.json
  src/api-service/__app__/queue_task_heartbeat/function.json
  src/api-service/__app__/queue_updates/function.json
  src/api-service/__app__/queue_webhooks/__init__.py
  src/api-service/__app__/queue_webhooks/function.json
  src/api-service/__app__/repro_vms/__init__.py
  src/api-service/__app__/repro_vms/function.json
  src/api-service/__app__/scaleset/__init__.py
  src/api-service/__app__/scaleset/function.json
  src/api-service/__app__/tasks/__init__.py
  src/api-service/__app__/tasks/function.json
  src/api-service/__app__/timer_daily/__init__.py
  src/api-service/__app__/timer_daily/function.json
  src/api-service/__app__/timer_proxy/function.json
  src/api-service/__app__/timer_repro/function.json
  src/api-service/__app__/timer_tasks/function.json
  src/api-service/__app__/webhooks/__init__.py
  src/api-service/__app__/webhooks/function.json
  src/api-service/__app__/webhooks_logs/__init__.py
  src/api-service/__app__/webhooks_logs/function.json
  src/api-service/__app__/webhooks_ping/__init__.py
  src/api-service/__app__/webhooks_ping/function.json
Labels: auto-merge, passed-integration-tests

#449 ensure consistency in doc generation by always sorting json keys
  docs/webhook_events.md
  src/pytypes/extra/generate-docs.py
Labels: auto-merge

#451 move to using machine_id rather than node_id
  src/api-service/__app__/onefuzzlib/pools.py
Labels: auto-merge, passed-integration-tests

#448 add unit test to verify functionality of nested list expansion
  src/agent/onefuzz/src/expand.rs
Labels: auto-merge

#446 add the task_id to the integration failure logs
  src/integration-tests/integration-test.py
Labels: auto-merge, passed-integration-tests

#453 Use `goblin` for more direct ELF handling
  src/agent/Cargo.lock
  src/agent/coverage/Cargo.toml
  src/agent/coverage/examples/block_coverage.rs
  src/agent/coverage/src/block/linux.rs
Labels: passed-integration-tests

#450 unify node resetting & deleting into delete/recreate
  src/api-service/__app__/agent_registration/__init__.py
  src/api-service/__app__/onefuzzlib/pools.py
Labels: auto-merge, passed-integration-tests

#447 Update the registration logic to print manual steps when adal authentication fails
  src/deployment/deploy.py
  src/deployment/registration.py
  src/deployment/requirements.txt
Labels: auto-merge, passed-integration-tests

#459 Update QueueClient with latest SAS URL upon renewing registration
  src/agent/onefuzz-supervisor/src/work.rs
Labels: auto-merge, passed-integration-tests

#458 remove early-exit from cleanup_nodes that broke dead node cleanup
  src/api-service/__app__/onefuzzlib/pools.py
Labels: auto-merge, passed-integration-tests

#454 allow supervisor tasks to be fully self-contained fuzzing tasks
  src/agent/onefuzz-agent/src/local/generic_crash_report.rs
  src/agent/onefuzz-agent/src/local/libfuzzer_crash_report.rs
  src/agent/onefuzz-agent/src/tasks/fuzz/supervisor.rs
  src/agent/onefuzz-agent/src/tasks/report/crash_report.rs
  src/agent/onefuzz-agent/src/tasks/report/generic.rs
  src/agent/onefuzz-agent/src/tasks/report/libfuzzer_report.rs
  src/agent/onefuzz/src/expand.rs
  src/agent/onefuzz/src/syncdir.rs
Labels: auto-merge, passed-integration-tests

#326 Storing secrets in azure keyvault
  src/api-service/__app__/notifications/__init__.py
  src/api-service/__app__/onefuzzlib/azure/creds.py
  src/api-service/__app__/onefuzzlib/notifications/ado.py
  src/api-service/__app__/onefuzzlib/notifications/github_issues.py
  src/api-service/__app__/onefuzzlib/notifications/teams.py
  src/api-service/__app__/onefuzzlib/orm.py
  src/api-service/__app__/onefuzzlib/secrets.py
  src/api-service/tests/test_secrets.py
  src/cli/onefuzz/backend.py
  src/deployment/azuredeploy.json
  src/pytypes/onefuzztypes/models.py
  src/pytypes/tests/test_models.py
Labels: breaking-change

#389 add keyvault management to administrative role
  src/deployment/deployment-role.json
Labels: auto-merge, breaking-change, passed-integration-tests

#462 use the unique-string based keyvault names
  src/api-service/__app__/onefuzzlib/secrets.py
  src/deployment/azuredeploy.json
Labels: auto-merge, passed-integration-tests

#427 update python prereqs
  docs/webhook_events.md
  src/api-service/__app__/containers/__init__.py
  src/api-service/__app__/onefuzzlib/azure/compute.py
  src/api-service/__app__/onefuzzlib/azure/containers.py
  src/api-service/__app__/onefuzzlib/azure/creds.py
  src/api-service/__app__/onefuzzlib/azure/disk.py
  src/api-service/__app__/onefuzzlib/azure/image.py
  src/api-service/__app__/onefuzzlib/azure/ip.py
  src/api-service/__app__/onefuzzlib/azure/monitor.py
  src/api-service/__app__/onefuzzlib/azure/network_mgmt_client.py
  src/api-service/__app__/onefuzzlib/azure/storage.py
  src/api-service/__app__/onefuzzlib/azure/subnet.py
  src/api-service/__app__/onefuzzlib/azure/vm.py
  src/api-service/__app__/onefuzzlib/azure/vmss.py
  src/api-service/__app__/onefuzzlib/pools.py
  src/api-service/__app__/onefuzzlib/tasks/config.py
  src/api-service/__app__/onefuzzlib/tasks/defs.py
  src/api-service/__app__/onefuzzlib/updates.py
  src/api-service/__app__/requirements.txt
  src/api-service/requirements-dev.txt
  src/ci/disable-py-cache.sh
  src/ci/enable-py-cache.sh
  src/cli/requirements.txt
  src/deployment/registration.py
  src/pytypes/onefuzztypes/enums.py
  src/pytypes/requirements.txt
  src/pytypes/tests/test_models.py
Labels: auto-merge, breaking-change, passed-integration-tests

#466 add context to command failures
  src/agent/debugger/src/debugger.rs
  src/agent/onefuzz-agent/src/tasks/coverage/recorder.rs
  src/agent/onefuzz-agent/src/tasks/fuzz/generator.rs
  src/agent/onefuzz-agent/src/tasks/fuzz/supervisor.rs
  src/agent/onefuzz-supervisor/src/commands.rs
  src/agent/onefuzz-supervisor/src/worker.rs
  src/agent/onefuzz/src/az_copy.rs
  src/agent/onefuzz/src/fs.rs
  src/agent/onefuzz/src/libfuzzer.rs
  src/agent/onefuzz/src/process.rs
Labels: auto-merge, passed-integration-tests

#469 Updating Windows Default Image from RS5-Pro to 20H2-Pro
  docs/supported-platforms.md
  src/api-service/__app__/onefuzzlib/repro.py
  src/cli/onefuzz/api.py
  src/cli/onefuzz/templates/__init__.py
Labels: auto-merge, passed-integration-tests

#471 update azure-mgmt-network to the latest version
  src/api-service/__app__/requirements.txt
Labels: auto-merge, passed-integration-tests

#475 Update expansion documentation to describe nested options as implemented
  docs/command-replacements.md
Labels: auto-merge

#472 use license rather than license_file for python packages
  src/cli/setup.py
  src/pytypes/setup.py
Labels: auto-merge, passed-integration-tests

#476 reimage long-lived nodes
  src/api-service/__app__/onefuzzlib/pools.py
Labels: auto-merge, passed-integration-tests

#477 remove unused Event generation from the pre-2.0.0 SignalR integration
  src/api-service/__app__/onefuzzlib/notifications/main.py
  src/pytypes/onefuzztypes/primitives.py
Labels: auto-merge, passed-integration-tests

#474 expose supervisor tasks that are fully self-contained fuzzing tasks in the service
  docs/webhook_events.md
  src/api-service/__app__/onefuzzlib/tasks/config.py
  src/api-service/__app__/onefuzzlib/tasks/defs.py
  src/cli/onefuzz/api.py
  src/cli/onefuzz/status/cache.py
  src/pytypes/onefuzztypes/enums.py
  src/pytypes/onefuzztypes/models.py
Labels: auto-merge, passed-integration-tests

#484 sync new inputs found by supervisor tasks
  src/agent/onefuzz-agent/src/tasks/fuzz/supervisor.rs
Labels: auto-merge, passed-integration-tests

#480 Expand tools_dir accessibility in variable expansion
  src/agent/onefuzz-agent/src/tasks/analysis/generic.rs
  src/agent/onefuzz-agent/src/tasks/merge/generic.rs
Labels: auto-merge, passed-integration-tests

#481 Add task_id & job_id to variable expansion
  docs/command-replacements.md
  src/agent/onefuzz-agent/src/tasks/analysis/generic.rs
  src/agent/onefuzz-agent/src/tasks/fuzz/generator.rs
  src/agent/onefuzz-agent/src/tasks/fuzz/supervisor.rs
  src/agent/onefuzz-agent/src/tasks/merge/generic.rs
  src/agent/onefuzz/src/expand.rs
Labels: auto-merge, passed-integration-tests

#485 Return an error when download_input fails
  src/agent/onefuzz-agent/src/tasks/utils.rs
Labels: auto-merge, passed-integration-tests
