Repository microsoft/onefuzz, pull requests merged in 2021-04, with the labels that each got.

#746 Added support for multi tenant authentication
  src/agent/onefuzz-supervisor/src/config.rs
  src/agent/onefuzz/src/auth.rs
  src/api-service/__app__/onefuzzlib/extension.py
  src/api-service/__app__/pool/__init__.py
  src/deployment/azuredeploy.json
  src/deployment/deploy.py
  src/deployment/registration.py
  src/pytypes/onefuzztypes/models.py
Labels: auto-merge, passed-integration-tests

#700 add log checking to refactored integration check
  src/api-service/__app__/onefuzzlib/agent_events.py
  src/api-service/__app__/onefuzzlib/azure/vm.py
  src/api-service/__app__/onefuzzlib/notifications/main.py
  src/api-service/__app__/onefuzzlib/reports.py
  src/api-service/__app__/onefuzzlib/tasks/main.py
  src/api-service/tests/test_report_parse.py
  src/integration-tests/integration-test.py
Labels: auto-merge, passed-integration-tests

#752 verify libfuzzer targets at the start of the task
  src/agent/onefuzz-agent/src/local/common.rs
  src/agent/onefuzz-agent/src/local/libfuzzer.rs
  src/agent/onefuzz-agent/src/tasks/config.rs
  src/agent/onefuzz-agent/src/tasks/coverage/libfuzzer_coverage.rs
  src/agent/onefuzz-agent/src/tasks/fuzz/libfuzzer_fuzz.rs
  src/agent/onefuzz-agent/src/tasks/merge/libfuzzer_merge.rs
  src/agent/onefuzz-agent/src/tasks/report/libfuzzer_report.rs
  src/agent/onefuzz/src/libfuzzer.rs
Labels: auto-merge, passed-integration-tests

#766 fix checking status codes for failure
  src/agent/onefuzz-supervisor/src/coordinator.rs
  src/agent/onefuzz/src/syncdir.rs
  src/agent/onefuzz/src/uploader.rs
  src/agent/reqwest-retry/src/lib.rs
Labels: auto-merge, passed-integration-tests

#767 simplify context for storage queue enqueue
  src/agent/storage-queue/src/azure_queue.rs
Labels: auto-merge, passed-integration-tests

#768 format deployment registration code
  src/deployment/registration.py
Labels: auto-merge, passed-integration-tests

#774 allow deployment to non-default subscriptions
  src/deployment/deploy.py
  src/deployment/registration.py
Labels: passed-integration-tests

#775 ignore benign error messages when checking integration test logs
  src/integration-tests/integration-test.py
Labels: passed-integration-tests

#663 local run UI
  src/agent/Cargo.lock
  src/agent/coverage/examples/block_coverage.rs
  src/agent/input-tester/src/appverifier.rs
  src/agent/input-tester/src/crash_detector.rs
  src/agent/onefuzz-agent/Cargo.toml
  src/agent/onefuzz-agent/build.rs
  src/agent/onefuzz-agent/src/local/cmd.rs
  src/agent/onefuzz-agent/src/local/common.rs
  src/agent/onefuzz-agent/src/local/generic_analysis.rs
  src/agent/onefuzz-agent/src/local/generic_crash_report.rs
  src/agent/onefuzz-agent/src/local/generic_generator.rs
  src/agent/onefuzz-agent/src/local/libfuzzer.rs
  src/agent/onefuzz-agent/src/local/libfuzzer_coverage.rs
  src/agent/onefuzz-agent/src/local/libfuzzer_crash_report.rs
  src/agent/onefuzz-agent/src/local/libfuzzer_fuzz.rs
  src/agent/onefuzz-agent/src/local/libfuzzer_merge.rs
  src/agent/onefuzz-agent/src/local/libfuzzer_regression.rs
  src/agent/onefuzz-agent/src/local/libfuzzer_test_input.rs
  src/agent/onefuzz-agent/src/local/mod.rs
  src/agent/onefuzz-agent/src/local/radamsa.rs
  src/agent/onefuzz-agent/src/local/test_input.rs
  src/agent/onefuzz-agent/src/local/tui.rs
  src/agent/onefuzz-agent/src/main.rs
  src/agent/onefuzz-agent/src/managed/cmd.rs
  src/agent/onefuzz-agent/src/tasks/coverage/recorder.rs
  src/agent/onefuzz-agent/src/tasks/fuzz/libfuzzer_fuzz.rs
  src/agent/onefuzz-agent/src/tasks/fuzz/supervisor.rs
  src/agent/onefuzz-agent/src/tasks/merge/generic.rs
  src/agent/onefuzz-supervisor/build.rs
  src/agent/onefuzz/src/az_copy.rs
  src/agent/onefuzz/src/blob/url.rs
  src/agent/onefuzz/src/fs.rs
  src/agent/onefuzz/src/input_tester.rs
  src/agent/onefuzz/src/process.rs
Labels: auto-merge, passed-integration-tests

#773 Added missing parameter for multi tenant deployment
  src/deployment/azuredeploy.json
Labels: auto-merge, passed-integration-tests

#780 set default value for ephemeral disks at the server request parser
  src/pytypes/onefuzztypes/requests.py
Labels: passed-integration-tests

#701 add retry with backoff to azcopy calls
  src/agent/Cargo.lock
  src/agent/onefuzz/Cargo.toml
  src/agent/onefuzz/src/az_copy.rs
  src/agent/reqwest-retry/Cargo.toml
Labels: auto-merge, passed-integration-tests

#781 Report the setup failure in the task when available
  src/api-service/__app__/onefuzzlib/agent_events.py
  src/api-service/__app__/onefuzzlib/workers/nodes.py
Labels: auto-merge, passed-integration-tests

#782 always use unix file endings when building libfuzzer-qemu wrappers
  src/cli/onefuzz/templates/libfuzzer.py
Labels: auto-merge, passed-integration-tests

#776 Wiring up the UI to the events
  src/agent/Cargo.lock
  src/agent/onefuzz-agent/src/local/cmd.rs
  src/agent/onefuzz-agent/src/local/common.rs
  src/agent/onefuzz-agent/src/local/generic_analysis.rs
  src/agent/onefuzz-agent/src/local/generic_crash_report.rs
  src/agent/onefuzz-agent/src/local/generic_generator.rs
  src/agent/onefuzz-agent/src/local/libfuzzer.rs
  src/agent/onefuzz-agent/src/local/libfuzzer_coverage.rs
  src/agent/onefuzz-agent/src/local/libfuzzer_crash_report.rs
  src/agent/onefuzz-agent/src/local/libfuzzer_fuzz.rs
  src/agent/onefuzz-agent/src/local/libfuzzer_merge.rs
  src/agent/onefuzz-agent/src/local/libfuzzer_regression.rs
  src/agent/onefuzz-agent/src/local/libfuzzer_test_input.rs
  src/agent/onefuzz-agent/src/local/radamsa.rs
  src/agent/onefuzz-agent/src/local/test_input.rs
  src/agent/onefuzz-agent/src/local/tui.rs
  src/agent/onefuzz-agent/src/tasks/fuzz/libfuzzer_fuzz.rs
  src/agent/onefuzz-telemetry/Cargo.toml
  src/agent/onefuzz-telemetry/src/lib.rs
Labels: auto-merge, passed-integration-tests

#784 don't refresh system stats when only reporting process stats
  src/agent/onefuzz-agent/src/tasks/fuzz/libfuzzer_fuzz.rs
  src/agent/onefuzz/src/system.rs
Labels: auto-merge, passed-integration-tests

#785 limit the amount of data recorded from libFuzzer's stderr
  src/agent/onefuzz-agent/src/tasks/fuzz/libfuzzer_fuzz.rs
Labels: auto-merge, passed-integration-tests

#786 combine execs/sec and iteration counts from multiple workers
  src/agent/onefuzz-agent/src/tasks/fuzz/libfuzzer_fuzz.rs
Labels: auto-merge, passed-integration-tests

#788 don't remove inputs once processed
  src/agent/onefuzz-agent/src/tasks/coverage/libfuzzer_coverage.rs
Labels: auto-merge, passed-integration-tests

#783 embed coverage debugger scripts
  src/agent/onefuzz-agent/src/tasks/coverage/libfuzzer_coverage.rs
  src/agent/onefuzz-agent/src/tasks/coverage/recorder.rs
Labels: auto-merge, passed-integration-tests

#787 invert the TUI event filter
  src/agent/onefuzz-agent/src/local/tui.rs
Labels: auto-merge, passed-integration-tests

#792 invert expect_crash_on_failure config option defaults
  src/agent/onefuzz-agent/src/local/libfuzzer_fuzz.rs
  src/agent/onefuzz-agent/src/tasks/fuzz/libfuzzer_fuzz.rs
Labels: auto-merge, passed-integration-tests

#793 add TaskConfig to crash_reported and regression_reported events
  docs/webhook_events.md
  src/api-service/__app__/onefuzzlib/notifications/main.py
  src/pytypes/onefuzztypes/events.py
Labels: auto-merge, passed-integration-tests

#796 add Timestamp to multiple models
  src/api-service/__app__/onefuzzlib/orm.py
  src/api-service/__app__/onefuzzlib/proxy.py
  src/api-service/__app__/onefuzzlib/task_event.py
  src/pytypes/onefuzztypes/models.py
  src/pytypes/onefuzztypes/webhooks.py
Labels: auto-merge, passed-integration-tests

#802 show task error details in logs
  src/agent/onefuzz-agent/src/managed/cmd.rs
Labels: auto-merge, passed-integration-tests

#799 remove unused import from coverage example
  src/agent/coverage/examples/block_coverage.rs
Labels: auto-merge, passed-integration-tests

#798 add basic context to every retried request
  src/agent/onefuzz-agent/src/tasks/merge/generic.rs
  src/agent/onefuzz-agent/src/tasks/merge/libfuzzer_merge.rs
  src/agent/onefuzz-agent/src/tasks/utils.rs
  src/agent/onefuzz-supervisor/src/config.rs
  src/agent/onefuzz-supervisor/src/coordinator.rs
  src/agent/onefuzz/src/auth.rs
  src/agent/onefuzz/src/blob/client.rs
  src/agent/onefuzz/src/machine_id.rs
  src/agent/onefuzz/src/syncdir.rs
  src/agent/onefuzz/src/uploader.rs
  src/agent/reqwest-retry/src/lib.rs
  src/agent/storage-queue/src/azure_queue.rs
  src/agent/storage-queue/src/lib.rs
Labels: auto-merge, passed-integration-tests

#797 only record the first failure if a task has multiple failures
  src/api-service/__app__/onefuzzlib/tasks/main.py
Labels: auto-merge, passed-integration-tests

#794 Allow the local run to work without copying the synced dirs
  src/agent/Cargo.lock
  src/agent/onefuzz-agent/Cargo.toml
  src/agent/onefuzz-agent/src/local/common.rs
  src/agent/onefuzz-agent/src/local/libfuzzer.rs
  src/agent/onefuzz-agent/src/local/radamsa.rs
  src/agent/onefuzz-agent/src/tasks/analysis/generic.rs
  src/agent/onefuzz-agent/src/tasks/fuzz/generator.rs
  src/agent/onefuzz-agent/src/tasks/fuzz/supervisor.rs
  src/agent/onefuzz-agent/src/tasks/generic/input_poller.rs
  src/agent/onefuzz-agent/src/tasks/regression/common.rs
  src/agent/onefuzz/src/syncdir.rs
Labels: auto-merge, passed-integration-tests

#800 Upgrade to tokio 1.5.0
  src/agent/Cargo.lock
  src/agent/onefuzz-agent/Cargo.toml
  src/agent/onefuzz-agent/src/local/common.rs
  src/agent/onefuzz-agent/src/local/generic_analysis.rs
  src/agent/onefuzz-agent/src/local/generic_crash_report.rs
  src/agent/onefuzz-agent/src/local/generic_generator.rs
  src/agent/onefuzz-agent/src/local/libfuzzer.rs
  src/agent/onefuzz-agent/src/local/libfuzzer_coverage.rs
  src/agent/onefuzz-agent/src/local/libfuzzer_crash_report.rs
  src/agent/onefuzz-agent/src/local/libfuzzer_fuzz.rs
  src/agent/onefuzz-agent/src/local/libfuzzer_merge.rs
  src/agent/onefuzz-agent/src/local/libfuzzer_regression.rs
  src/agent/onefuzz-agent/src/local/libfuzzer_test_input.rs
  src/agent/onefuzz-agent/src/local/radamsa.rs
  src/agent/onefuzz-agent/src/local/test_input.rs
  src/agent/onefuzz-agent/src/local/tui.rs
  src/agent/onefuzz-agent/src/main.rs
  src/agent/onefuzz-agent/src/tasks/analysis/generic.rs
  src/agent/onefuzz-agent/src/tasks/coverage/libfuzzer_coverage.rs
  src/agent/onefuzz-agent/src/tasks/fuzz/generator.rs
  src/agent/onefuzz-agent/src/tasks/fuzz/libfuzzer_fuzz.rs
  src/agent/onefuzz-agent/src/tasks/fuzz/supervisor.rs
  src/agent/onefuzz-agent/src/tasks/generic/input_poller.rs
  src/agent/onefuzz-supervisor/Cargo.toml
  src/agent/onefuzz-supervisor/src/agent.rs
  src/agent/onefuzz-supervisor/src/debug.rs
  src/agent/onefuzz-supervisor/src/main.rs
  src/agent/onefuzz-supervisor/src/setup.rs
  src/agent/onefuzz-telemetry/Cargo.toml
  src/agent/onefuzz/Cargo.toml
  src/agent/onefuzz/src/asan.rs
  src/agent/onefuzz/src/fs.rs
  src/agent/onefuzz/src/heartbeat.rs
  src/agent/onefuzz/src/jitter.rs
  src/agent/onefuzz/src/process.rs
  src/agent/onefuzz/src/uploader.rs
  src/agent/onefuzz/src/utils.rs
  src/agent/reqwest-retry/Cargo.toml
  src/agent/storage-queue/Cargo.toml
  src/agent/storage-queue/src/local_queue.rs
  src/proxy-manager/Cargo.lock
  src/proxy-manager/Cargo.toml
  src/proxy-manager/src/main.rs
  src/proxy-manager/src/proxy.rs
Labels: auto-merge, passed-integration-tests

#804 remove timestamp from WebhookMessageLog model
  src/api-service/__app__/onefuzzlib/webhooks.py
  src/pytypes/onefuzztypes/webhooks.py
Labels: auto-merge, passed-integration-tests

#805 allow extra fields in Events
  docs/webhook_events.md
  src/pytypes/onefuzztypes/events.py
Labels: auto-merge, passed-integration-tests

#778 Add example job pipelines
  README.md
  contrib/README.md
  contrib/onefuzz-job-azure-devops-pipeline/README.md
  contrib/onefuzz-job-azure-devops-pipeline/ado-work-items.json
  contrib/onefuzz-job-azure-devops-pipeline/azure-pipelines.yml
  contrib/onefuzz-job-github-actions/README.md
  contrib/onefuzz-job-github-actions/github-issues.json
  contrib/onefuzz-job-github-actions/github-pipeline.yml
Labels: auto-merge

#803 catch VM SKU & VM Image generation mismatch failures
  src/api-service/__app__/onefuzzlib/azure/vmss.py
Labels: auto-merge, passed-integration-tests

#807 disable expect_crash_on_failure by default in more places
  src/cli/onefuzz/templates/libfuzzer.py
Labels: auto-merge, passed-integration-tests

#808 add additional privilages required to deployment role
  src/deployment/deployment-role.json
Labels: auto-merge

#809 refactor SyncDir and blob container url
  src/agent/onefuzz-agent/src/local/common.rs
  src/agent/onefuzz-agent/src/tasks/analysis/generic.rs
  src/agent/onefuzz-agent/src/tasks/coverage/libfuzzer_coverage.rs
  src/agent/onefuzz-agent/src/tasks/coverage/recorder.rs
  src/agent/onefuzz-agent/src/tasks/fuzz/generator.rs
  src/agent/onefuzz-agent/src/tasks/fuzz/libfuzzer_fuzz.rs
  src/agent/onefuzz-agent/src/tasks/fuzz/supervisor.rs
  src/agent/onefuzz-agent/src/tasks/generic/input_poller.rs
  src/agent/onefuzz-agent/src/tasks/merge/generic.rs
  src/agent/onefuzz-agent/src/tasks/merge/libfuzzer_merge.rs
  src/agent/onefuzz-agent/src/tasks/regression/common.rs
  src/agent/onefuzz-supervisor/src/setup.rs
  src/agent/onefuzz/src/blob/url.rs
  src/agent/onefuzz/src/syncdir.rs
Labels: auto-merge, passed-integration-tests

#816 Add optional coverage to `input-tester` API
  src/agent/input-tester/src/crash_detector.rs
  src/agent/input-tester/src/lib.rs
  src/agent/input-tester/src/tester.rs
Labels: passed-integration-tests

#828 update azure-storage-blob to 12.8.1
  src/api-service/__app__/requirements.txt
Labels: auto-merge, passed-integration-tests

#827 update azure-storage-queue to 12.1.6
  src/api-service/__app__/requirements.txt
Labels: auto-merge, passed-integration-tests

#823 update azure-mgmt-storage to 17.1.0
  src/api-service/__app__/requirements.txt
  src/utils/add-corpus-storage-accounts/requirements.txt
Labels: auto-merge, passed-integration-tests

#822 update azure-mgmt-resource to 16.1.0
  src/api-service/__app__/requirements.txt
Labels: auto-merge, passed-integration-tests

#821 update azure-cli to 2.21.1
  src/cli/requirements.txt
  src/deployment/requirements.txt
Labels: auto-merge, passed-integration-tests

#835 add context to Expand errors
  src/agent/onefuzz/src/expand.rs
Labels: passed-integration-tests

#833 move to Instant.elapsed() instead of time::Sleep timer
  src/agent/onefuzz-supervisor/src/agent.rs
Labels: passed-integration-tests

#834 when processing node updates, don't wait on the node in cases it should be stopped
  src/api-service/__app__/onefuzzlib/workers/nodes.py
Labels: auto-merge, passed-integration-tests

#832 handle queues vanishing during peek
  src/api-service/__app__/onefuzzlib/azure/queue.py
Labels: auto-merge, passed-integration-tests

#825 fix cli client registration
  src/cli/onefuzz/api.py
  src/deployment/deploy.py
  src/deployment/registration.py
Labels: auto-merge, passed-integration-tests
