Repository microsoft/onefuzz, pull requests merged in 2021-08, with the labels that each got.

#1124 update memoization to 0.4.0
  src/api-service/__app__/requirements.txt
  src/cli/requirements.txt
Labels: auto-merge, passed-integration-tests

#1123 expose `coverage` as an optional directory that gets synced to supervisor tasks
  docs/command-replacements.md
  src/agent/onefuzz-agent/src/tasks/fuzz/supervisor.rs
  src/agent/onefuzz/src/expand.rs
  src/api-service/__app__/onefuzzlib/tasks/defs.py
Labels: auto-merge, passed-integration-tests

#1109 redirect output of supervisor by executing a child process
  src/agent/onefuzz-supervisor/src/failure.rs
  src/agent/onefuzz-supervisor/src/main.rs
  src/agent/onefuzz/src/fs.rs
  src/runtime-tools/linux/run.sh
  src/runtime-tools/win64/onefuzz-run.ps1
  src/runtime-tools/win64/onefuzz-silent-exit.reg
  src/runtime-tools/win64/onefuzz.ps1
  src/runtime-tools/win64/setup.ps1
Labels: passed-integration-tests

#1152 Synchronize update of Linux dependencies
  src/agent/Cargo.lock
  src/agent/coverage/Cargo.toml
  src/agent/onefuzz/Cargo.toml
Labels: auto-merge
